name: Check Velero Manifest

on:
  push:
    branches:
      - ci-verify-manifest

jobs:
  check-velero-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout repository
        run: |
          ls -la
          git status

      - name: Install kubectl
        run: |
          # Install kubectl
          KUBECTL_VERSION="v1.21.0" # Replace with the desired version
          curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client
      # - uses: azure/setup-kubectl@v3
      #   with:
      #     version: '<version>' # default is latest stable
      #   id: install

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: 'v0.14.0'
          node_image: 'kindest/node:v1.19.16'

      - name: Install velero
        run: |
          wget https://github.com/vmware-tanzu/velero/releases/download/v1.11.1/velero-v1.11.1-linux-amd64.tar.gz
          tar -xvf velero-v1.11.1-linux-amd64.tar.gz
          cd velero-v1.11.1-linux-amd64
          sudo cp velero /usr/local/bin
          velero version
  
      - name: Run trial commands
        run: |
          cd charts/velero
          # Preparing manifests using velero
          velero install --crds-only --dry-run -o yaml | kubectl apply --dry-run=client -f - -o yaml > velero_manifest.yaml
          kubectl apply --dry-run=none -f crds/ -o yaml > crds_manifest.yaml

          ls -la
          diff velero_manifest.yaml crds_manifest.yaml > diff_result.txt
          echo $?
