name: Check Velero Manifest

on:
  push:
    branches:
      - ci-verify-manifest

jobs:
  check-velero-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: 'v0.14.0'
          node_image: 'kindest/node:v1.19.16'

      - name: Install velero
        run: |
          wget https://github.com/vmware-tanzu/velero/releases/download/v1.11.1/velero-v1.11.1-linux-amd64.tar.gz
          tar -xvf velero-v1.11.1-linux-amd64.tar.gz
          cd velero-v1.11.1-linux-amd64
          sudo cp velero /usr/local/bin
          velero version

      - name: Compare manifests
        run: |
          cd charts/velero
          # Preparing manifests using velero
          velero install --crds-only --dry-run -o yaml | kubectl apply --dry-run=client -f - -o yaml > velero_manifest.yaml
          kubectl apply --dry-run=client -f crds/ -o yaml > crds_manifest.yaml

          # Compare the two files using diff
          set +e
          difference=$(diff -y --color velero_manifest.yaml crds_manifest.yaml)
          if [ -z "$difference" ]; then
              echo "Files are synced. No differences found."
          else
              echo "Differences between $file1 and $file2:"
              echo "$difference"
              exit 1
          fi
  
      - name: Archive manifests
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: velero_manifest
          path: |
            charts/velero/velero_manifest.yaml
            charts/velero/crds_manifest.yaml
