name: Check Velero Manifest

on:
  push:
    branches:
      - ci-verify-manifest

jobs:
  check-velero-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: 'v0.14.0'
          node_image: 'kindest/node:v1.19.16'

      - name: Install velero
        run: |
          wget https://github.com/vmware-tanzu/velero/releases/download/v1.11.1/velero-v1.11.1-linux-amd64.tar.gz
          tar -xvf velero-v1.11.1-linux-amd64.tar.gz
          cd velero-v1.11.1-linux-amd64
          sudo cp velero /usr/local/bin
          velero version

      - name: Compare manifests
        run: |
          cd charts/velero

          # Preparing manifests using velero
          velero_manifest=$(velero install --crds-only --dry-run -o yaml)
          crds_manifest=$(kubectl apply --dry-run=client -f crds/ -o yaml)
      
          # Compare the two manifests using diff
          difference=$(diff -y --color <(echo "$velero_manifest") <(echo "$crds_manifest") || true)
      
          # Check if there are differences
          if [ -z "$difference" ]; then
            echo "Files are synced. No differences found."
          else
            echo "Differences between Velero manifests and CRDs:"
            echo "$difference"
            exit 1
          fi